sonar.projectKey=ennduka86-spec_Threat-Hunting-Toolkit-
sonar.organization=ennduka86-spec
sonar.host.url=https://sonarcloud.io

sonar.python.version=3.10
sonar.sources=.
sonar.exclusions=**/__pycache__/**,**/*.md,**/*.json

sonar.tests=tests
sonar.test.inclusions=**/tests/**
sonar.coverageReportPaths=coverage.xml

sonar.sourceEncoding=UTF-8
